# Generated by Django 3.0.6 on 2020-06-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('subInventario', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pdv', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
