# Generated by Django 3.0.6 on 2020-06-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('subInventario', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('pdv', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ordenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilusionesAPI.Almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilusionesAPI.Producto')),
            ],
        ),
    ]
