# Generated by Django 3.0.6 on 2020-06-03 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilusionesAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ilusionesAPI.Estatus'),
        ),
    ]
