# Generated by Django 3.0.6 on 2020-06-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilusionesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='folio',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='ilusionesAPI.Recepcion'),
            preserve_default=False,
        ),
    ]
