# Generated by Django 3.0.6 on 2020-06-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilusionesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='subInventario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
