# Generated by Django 3.0.6 on 2020-06-04 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilusionesAPI', '0002_auto_20200603_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('clave', models.CharField(error_messages={'unique': 'Ya existe actualmente esta clave'}, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='almacen',
            name='subInventario',
            field=models.CharField(error_messages={'unique': 'Ya existe actualmente esta clave'}, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ilusionesAPI.Orden'),
        ),
    ]
