# Generated by Django 3.0.6 on 2020-06-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilusionesAPI', '0003_auto_20200603_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='orden',
        ),
    ]
