# Generated by Django 3.0.6 on 2020-06-04 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilusionesAPI', '0004_remove_ordencompra_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='orden',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ilusionesAPI.Orden'),
        ),
    ]
